### ISSUE TITLE
Can't resolve 'pipwerks-scorm-api-wrapper' in '/Users/..../node_modules/react-scorm-provider/lib'

### ISSUE THREAD

**Issue by Sydwelll** [JayV30/react-scorm-provider#2]
Hello, i just installed the package and started the project, and i got this error. An idea of ​​where the error came from ?

Thank you

**Comment by JayV30** [comment]
Sorry about that! looks like I'm a big dummy and included the 'pipwerks-scorm-api-wrapper' library as a devDependency instead of a dependency. I'll publish a new version later today which I believe would solve that issue.

Sorry for the inconvenience.

**Comment by JayV30** [comment]
I have published version 0.1.3 to npm with updated dependencies. Hopefully this resolves your issue. Let me know. If not, I'll need to do more research into the issue.

**Comment by JayV30** [comment]
Closing this as resolved.
