### ISSUE TITLE
How to wait for the API to be connected

### ISSUE THREAD

**Issue by nooxx** [JayV30/react-scorm-provider#3]
Hi there,

First of all, really great wrapper that simplifies a lot of things so thank you for that.

My only issue is that I'm trying to wait for the SCORM API to be ready so I can fetch the data previously set in suspend data, any idea how to achieve this?

Thanks,
Arno

**Comment by JayV30** [comment]
After the SCORM API connecting is made, props.sco.suspendData should be automatically populated with the suspendData from the LMS.

props.sco object can be accessed using the withScorm wrapper.

If for some reason the suspendData is not loading after the SCORM API connection is made, you can manually call props.sco.getSuspendData(), which will then update the props.sco.suspendData object.

I wrote a quick [gist that might help demonstrate](https://gist.github.com/JayV30/298b1520b26cf1dc122ec7a3df2c3f3d)

Additionally, please note that the suspend data implementation in this library is opinionated - suspend data is a stringified object and will attempt to parse it as such. So if you have existing suspend data that is not a JSON.stringify()'d object, you may run in to errors.

**Comment by nooxx** [comment]
Brilliant, thanks!
